/* AUTHENTICATION */

export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGIN_RCV = "AUTH_LOGIN_RECV";

export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_REGISTER_RCV = "AUTH_REGISTER_RCV";
